"use client";

import { createContext, useActionState, useContext, useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import type { BoardCellValue, BoardColumn } from "@/lib/boards/types";
import type { NewcustSnapshot } from "@/lib/repo/supabase/supabaseBoardsSource";
import { visibleNewcustItems } from "@/lib/newcust/filters";
import {
  addNewcustColumn, addNewcustGroup, createNewcustItem, deleteNewcustColumn, renameNewcustGroup,
  importNewcustCsv, renameNewcustColumn, undoNewcustCsv, updateNewcustCell, updateNewcustItem,
  saveNewcustView,
  type NewcustActionState,
} from "@/app/(app)/newcust/actions";
import styles from "./newcust-board.module.css";

const initial: NewcustActionState = { ok: false, message: "" };
const StructureContext = createContext(true);
const GroupEditContext = createContext<(id: string) => void>(() => undefined);

function ActionForm({ action, children, className }: { action: typeof createNewcustItem; children: React.ReactNode; className?: string }) {
  const router = useRouter();
  const [state, formAction, pending] = useActionState(action, initial);
  useEffect(() => { if (state.ok) router.refresh(); }, [state.ok, state.message, router]);
  return <form action={formAction} className={className} aria-busy={pending} onSubmit={(event) => { if (event.currentTarget.querySelector(`.${styles.danger}`) && !window.confirm("이 작업은 되돌릴 수 없습니다. 계속할까요?")) event.preventDefault(); }}>{children}<span className={state.message && !state.ok ? styles.formError : styles.srOnly} role="status">{pending ? "저장 중" : state.message}</span></form>;
}

function CellEditor({ boardId, itemId, column, value }: { boardId: string; itemId: string; column: BoardColumn; value: BoardCellValue }) {
  const options = column.options_jsonb?.options ?? [];
  const common = <><input type="hidden" name="boardId" value={boardId}/><input type="hidden" name="itemId" value={itemId}/><input type="hidden" name="key" value={column.key}/></>;
  if (column.type === "file") return <span>{Array.isArray(value) ? value.map((entry) => typeof entry === "string" ? entry : entry.name).join(", ") : ""}</span>;
  return <ActionForm action={updateNewcustCell} className={styles.cellForm}>{common}{column.type === "select" ? <select name="value" defaultValue={String(value ?? "")} aria-label={`${column.label} 변경`} onChange={(event) => event.currentTarget.form?.requestSubmit()}><option value="">미설정</option>{options.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select> : <input name="value" type={column.type === "date" ? "date" : column.type === "number" ? "number" : column.type === "phone" ? "tel" : "text"} defaultValue={String(value ?? "")} aria-label={`${column.label} 변경`} onKeyDown={(event) => { if (event.key === "Enter") event.currentTarget.form?.requestSubmit(); if (event.key === "Escape") { event.currentTarget.value = String(value ?? ""); event.currentTarget.blur(); } }} onBlur={(event) => { if (event.currentTarget.value !== String(value ?? "")) event.currentTarget.form?.requestSubmit(); }}/>}</ActionForm>;
}

function ColumnMenu({ boardId, column, canManageStructure = true }: { boardId: string; column: BoardColumn; canManageStructure?: boolean }) {
  canManageStructure = useContext(StructureContext) && canManageStructure;
  if (!canManageStructure) return <button disabled title="보드 구조 변경은 보드 소유자 또는 관리자만 가능합니다." aria-label={`${column.label} 컬럼 메뉴 사용 불가`}>⌄</button>;
  return <span className={styles.columnMenu}><ActionForm action={renameNewcustColumn} className={styles.inlineColumnName}><input type="hidden" name="boardId" value={boardId}/><input type="hidden" name="columnId" value={column.id}/><input name="label" defaultValue={column.label} aria-label={`${column.label} 컬럼 제목 인라인 변경`} onKeyDown={(event) => { if (event.key === "Enter") event.currentTarget.form?.requestSubmit(); if (event.key === "Escape") { event.currentTarget.value=column.label; event.currentTarget.blur(); } }} onBlur={(event) => { if (event.currentTarget.value.trim() && event.currentTarget.value !== column.label) event.currentTarget.form?.requestSubmit(); }}/></ActionForm><details><summary aria-label={`${column.label} 위험 작업`}>⌄</summary><div className={styles.popover}><ActionForm action={deleteNewcustColumn}><input type="hidden" name="boardId" value={boardId}/><input type="hidden" name="columnId" value={column.id}/><input type="hidden" name="key" value={column.key}/><button className={styles.danger}>컬럼 삭제</button></ActionForm></div></details></span>;
}

function NewItemControl({ boardId, groupId, canManageStructure }: { boardId: string; groupId: string; canManageStructure: boolean }) {
  const onGroupCreated=useContext(GroupEditContext);
  const router=useRouter(); const [groupState, createGroup, groupPending]=useActionState(addNewcustGroup, initial);
  useEffect(() => { if (groupState.ok && groupState.groupId) { onGroupCreated(groupState.groupId); router.refresh(); } }, [groupState, onGroupCreated, router]);
  return <div className={styles.newItemControl}><ActionForm action={createNewcustItem}><input type="hidden" name="boardId" value={boardId}/><input type="hidden" name="groupId" value={groupId}/><input type="hidden" name="title" value="새 업체"/><button className={styles.primary}>새 업체</button></ActionForm><details><summary aria-label="새 업체 추가 옵션">▾</summary><div className={styles.popover}>{canManageStructure ? <form action={createGroup} aria-busy={groupPending}><input type="hidden" name="boardId" value={boardId}/><button>새 그룹</button><span role="status" className={styles.srOnly}>{groupState.message}</span></form> : <button disabled title="보드 소유자 또는 관리자만 가능합니다.">새 그룹</button>}<CsvImport boardId={boardId} groupId={groupId}/></div></details></div>;
}

export function NewcustBoard({ snapshot, currentUserId, currentUserName, canManageStructure }: { snapshot: NewcustSnapshot; currentUserId: string; currentUserName: string; canManageStructure: boolean }) {
  const [query, setQuery] = useState(""); const [assignee, setAssignee] = useState(""); const [status, setStatus] = useState(""); const [sort, setSort] = useState("");
  const [viewKind, setViewKind] = useState<"table" | "kanban" | "calendar">("table");
  const [groupBy, setGroupBy] = useState("board"); const [viewDirty, setViewDirty] = useState(false);
  const [activeView, setActiveView] = useState("default");
  const [editingGroupId, setEditingGroupId] = useState<string | null>(null);
  const [hidden, setHidden] = useState<string[]>([]); const [collapsed, setCollapsed] = useState<string[]>([]); const [selected, setSelected] = useState<string | null>(null);
  const drawerRef = useRef<HTMLDialogElement>(null);
  const drawerTriggerRef = useRef<HTMLButtonElement | null>(null);
  const columns = snapshot.columns.filter((column) => !hidden.includes(column.id));
  const filteredItems = useMemo(() => visibleNewcustItems(snapshot.items, snapshot.columns, { query, assignee, status, sort, currentUserId }), [snapshot, query, assignee, status, sort, currentUserId]);
  const items = groupBy === "status" ? [] : filteredItems;
  const selectedItem = snapshot.items.find((item) => item.id === selected);
  useEffect(() => { if (selectedItem && !drawerRef.current?.open) drawerRef.current?.showModal(); }, [selectedItem]);
  const closeDrawer = () => { drawerRef.current?.close(); setSelected(null); window.setTimeout(() => drawerTriggerRef.current?.focus(), 0); };
  const statusOptions = snapshot.columns.find((column) => column.key === "contact_status")?.options_jsonb?.options ?? [];
  return <StructureContext.Provider value={canManageStructure}><GroupEditContext.Provider value={setEditingGroupId}><main className={`${styles.board} ${canManageStructure ? "" : styles.structureReadOnly}`}>
    {!canManageStructure && <p className={styles.permissionNotice}>보드 구조 변경은 보드 소유자 또는 관리자만 가능합니다. 업체 데이터 편집은 계속할 수 있습니다.</p>}
    <details className={styles.boardInfo}><summary>보드 정보</summary><div className={styles.popover}><strong>{snapshot.board.name}</strong><span>{snapshot.board.description}</span><span>기본 보기: 표</span></div></details>
    <header className={styles.header}><div><p className={styles.eyebrow}>고객 관계 관리</p><h1>{snapshot.board.icon} {snapshot.board.name}</h1><p>{snapshot.board.description}</p></div><div className={styles.headerActions}><button aria-label={`참여자 ${currentUserName}`}>{currentUserName.slice(0, 1)}</button><button>활동</button><details><summary aria-label="더보기 메뉴">•••</summary><div className={styles.popover}><CsvImport boardId={snapshot.board.id} groupId={snapshot.groups[0]?.id ?? ""}/><Link href="/boards">보드 관리로 이동</Link></div></details></div></header>
    <nav className={styles.views} aria-label="보드 보기"><button className={activeView === "default" ? styles.activeView : undefined} aria-current={activeView === "default" ? "page" : undefined} onClick={() => { setActiveView("default"); setViewKind("table"); setGroupBy("board"); setSort(""); setHidden([]); setViewDirty(false); }}>기본 표</button>{snapshot.views.map((view) => <button key={view.id} className={activeView === view.id ? styles.activeView : undefined} aria-current={activeView === view.id ? "page" : undefined} onClick={() => { setActiveView(view.id); setViewKind(view.kind as "table" | "kanban" | "calendar"); setGroupBy(typeof view.filters_jsonb.groupBy === "string" ? view.filters_jsonb.groupBy : "board"); const first=view.sort_jsonb[0] as { key?: unknown } | undefined; setSort(typeof first?.key === "string" ? first.key : ""); setHidden(snapshot.columns.filter((column) => !view.visible_columns_jsonb.includes(column.id)).map((column) => column.id)); setViewDirty(false); }}>{view.name}</button>)}<details><summary aria-label="새 보기 추가">＋ 보기</summary><div className={styles.popover}>{([['table','표'],['kanban','칸반'],['calendar','캘린더']] as const).map(([kind,label]) => <button key={kind} onClick={() => { setActiveView("draft"); setViewKind(kind); setViewDirty(true); }}>{label}</button>)}</div></details></nav>
    <section className={styles.toolbar} aria-label="보드 도구"><NewItemControl boardId={snapshot.board.id} groupId={snapshot.groups[0]?.id ?? ""} canManageStructure={canManageStructure}/><label className={styles.search}>⌕<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="업체 검색" aria-label="업체 검색"/></label><select value={assignee} onChange={(event) => setAssignee(event.target.value)} aria-label="담당자 필터"><option value="">담당자</option><option value="mine">내 담당</option><option value="none">미배정</option></select><select value={status} onChange={(event) => setStatus(event.target.value)} aria-label="연락 상태 필터"><option value="">필터</option>{statusOptions.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select><select value={sort} onChange={(event) => { setSort(event.target.value); setViewDirty(true); }} aria-label="임시 정렬"><option value="">정렬</option><option value="name">업체명</option><option value="revenue">예상 매출 높은 순</option></select><select value={groupBy} onChange={(event) => { setGroupBy(event.target.value); setViewDirty(true); }} aria-label="임시 그룹 기준"><option value="board">기본 그룹</option><option value="status">연락 상태</option></select><details><summary>컬럼 숨기기</summary><div className={styles.popover}>{snapshot.columns.map((column) => <label key={column.id}><input type="checkbox" checked={!hidden.includes(column.id)} onChange={() => { setHidden((before) => before.includes(column.id) ? before.filter((id) => id !== column.id) : [...before, column.id]); setViewDirty(true); }}/>{column.label}</label>)}</div></details>{viewDirty && <ActionForm action={saveNewcustView}><input type="hidden" name="boardId" value={snapshot.board.id}/><input type="hidden" name="name" value={`${viewKind === 'table' ? '표' : viewKind === 'kanban' ? '칸반' : '캘린더'} 보기`}/><input type="hidden" name="kind" value={viewKind}/><input type="hidden" name="sort" value={sort}/><input type="hidden" name="groupBy" value={groupBy}/><input type="hidden" name="visibleColumns" value={JSON.stringify(columns.map((column) => column.id))}/><button>새 보기로 저장</button></ActionForm>}</section>
    {viewKind !== "table" && <section className={styles.group} aria-label={`${viewKind === "kanban" ? "칸반" : "캘린더"} 보기`}><h2>{viewKind === "kanban" ? "칸반" : "캘린더"}</h2><ul>{filteredItems.map((item) => <li key={item.id}>{item.title}</li>)}</ul></section>}
    {viewKind === "table" && groupBy === "status" && <div className={styles.tableViewport}>{statusOptions.map((option) => { const statusItems=filteredItems.filter((item) => item.values.contact_status === option.id); return <section className={styles.group} key={option.id}><div className={styles.groupHeader} style={{ "--group-color": option.color ?? "#579bfc" } as React.CSSProperties}><h2>{option.label}</h2><span>{statusItems.length}개</span></div><ul>{statusItems.map((item) => <li key={item.id}><button className={styles.rowTitle} onClick={(event) => { drawerTriggerRef.current=event.currentTarget; setSelected(item.id); }}>{item.title}</button></li>)}</ul></section>; })}</div>}
    {viewKind === "table" && <div className={styles.tableViewport}>{snapshot.groups.map((group) => {
      const groupItems = items.filter((item) => item.group_id === group.id);
      const isCollapsed = collapsed.includes(group.id);
      return <section className={styles.group} key={group.id}>
        <div className={styles.groupHeader} style={{ "--group-color": group.color ?? "#579bfc" } as React.CSSProperties}>
          <button aria-expanded={!isCollapsed} onClick={() => setCollapsed((before) => before.includes(group.id) ? before.filter((id) => id !== group.id) : [...before, group.id])}>{isCollapsed ? "▶" : "▼"}</button>
          {editingGroupId === group.id ? <ActionForm action={renameNewcustGroup} className={styles.inlineGroupName}><input type="hidden" name="boardId" value={snapshot.board.id}/><input type="hidden" name="groupId" value={group.id}/><input name="name" defaultValue={group.name === "새 그룹" ? "" : group.name} placeholder="그룹 이름" aria-label="새 그룹 인라인 이름" autoFocus onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); event.currentTarget.form?.requestSubmit(); setEditingGroupId(null); } if (event.key === "Escape") { event.currentTarget.value=group.name; setEditingGroupId(null); } }} onBlur={(event) => { if (event.currentTarget.value.trim()) { event.currentTarget.form?.requestSubmit(); setEditingGroupId(null); } }}/></ActionForm> : <button className={styles.groupNameButton} disabled={!canManageStructure} title={canManageStructure ? "그룹 이름 변경" : "보드 소유자 또는 관리자만 그룹 이름을 변경할 수 있습니다."} onClick={() => setEditingGroupId(group.id)}>{group.name}</button>}
          <span>{groupItems.length}개</span>
          {canManageStructure ? <button disabled title="그룹 삭제는 다음 구조 관리 단계에서 지원됩니다." aria-label={`${group.name} 삭제 준비 중`}>•••</button> : <button disabled title="보드 소유자 또는 관리자만 그룹 구조를 변경할 수 있습니다." aria-label={`${group.name} 구조 변경 권한 없음`}>•••</button>}
        </div>
        {!isCollapsed && <table><thead><tr><th aria-label="전체 선택"><input type="checkbox" aria-label={`${group.name} 전체 선택`}/></th><th className={styles.sticky}>업체명</th><th>업데이트</th><th>담당자</th>{columns.map((column) => <th key={column.id}>{column.label}<ColumnMenu boardId={snapshot.board.id} column={column}/></th>)}<th>{canManageStructure ? <ColumnCenter boardId={snapshot.board.id}/> : <button disabled title="보드 소유자 또는 관리자만 컬럼을 추가할 수 있습니다.">＋</button>}</th></tr></thead><tbody>{groupItems.map((item) => <tr key={item.id}><td><input type="checkbox" aria-label={`${item.title} 선택`}/></td><td className={styles.sticky}><button className={styles.rowTitle} onClick={(event) => { drawerTriggerRef.current = event.currentTarget; setSelected(item.id); }}>{item.title}</button></td><td><span className={styles.updateBubble} aria-label={`${item.title} 업데이트 없음`}>—</span></td><td><ActionForm action={updateNewcustItem} className={styles.cellForm}><input type="hidden" name="boardId" value={snapshot.board.id}/><input type="hidden" name="itemId" value={item.id}/><input type="hidden" name="field" value="assigned_to"/><select name="value" defaultValue={item.assigned_to ?? ""} aria-label={`${item.title} 담당자 변경`} onChange={(event) => event.currentTarget.form?.requestSubmit()}><option value="">미배정</option><option value={currentUserId}>{currentUserName}</option></select></ActionForm></td>{columns.map((column) => <td key={column.id}><CellEditor boardId={snapshot.board.id} itemId={item.id} column={column} value={item.values[column.key] ?? null}/></td>)}<td/></tr>)}<tr className={styles.emptyRow}><td/><td className={styles.sticky}><ActionForm action={createNewcustItem}><input type="hidden" name="boardId" value={snapshot.board.id}/><input type="hidden" name="groupId" value={group.id}/><input name="title" placeholder="＋ 업체 추가" aria-label={`${group.name}에 업체 추가`}/></ActionForm></td><td colSpan={columns.length + 3}/></tr></tbody></table>}
      </section>;
    })}</div>}
    <button disabled className={styles.addGroup} title={canManageStructure ? "상단 새 업체 화살표에서 새 그룹을 추가할 수 있습니다." : "보드 소유자 또는 관리자만 그룹을 추가할 수 있습니다."}>＋ 새 그룹</button>
    {selectedItem && <dialog className={styles.drawer} ref={drawerRef} tabIndex={-1} onCancel={(event) => { event.preventDefault(); closeDrawer(); }} aria-label={`${selectedItem.title} 상세`}><div className={styles.drawerHeader}><div><p className={styles.eyebrow}>업체 상세</p><h2>{selectedItem.title}</h2></div><button aria-label="상세 닫기" onClick={closeDrawer}>×</button></div><ActionForm action={updateNewcustItem}><input type="hidden" name="boardId" value={snapshot.board.id}/><input type="hidden" name="itemId" value={selectedItem.id}/><input type="hidden" name="field" value="title"/><label>업체명<input name="value" defaultValue={selectedItem.title}/></label><button>저장</button></ActionForm><section><h3>담당자</h3><p>{selectedItem.assigned_to ? currentUserName : "미배정"}</p></section><section><h3>메모 / 활동</h3><p>셀 변경 내역과 고객 메모를 이곳에서 확인합니다.</p></section><section><h3>다음 행동</h3><p>{String(selectedItem.values.next_contact ?? "다음 연락일을 정해 주세요.")}</p></section></dialog>}
  </main></GroupEditContext.Provider></StructureContext.Provider>;
}

function ColumnCenter({ boardId }: { boardId: string }) { const [query, setQuery] = useState(""); const types = [{ type: "select", label: "상태" }, { type: "person", label: "담당자" }, { type: "date", label: "날짜" }, { type: "number", label: "금액" }, { type: "text", label: "텍스트" }, { type: "phone", label: "전화" }].filter((item) => item.label.includes(query)); return <details className={styles.columnCenter}><summary aria-label="컬럼 추가">＋</summary><div className={styles.columnPanel}><h3>컬럼 센터</h3><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="컬럼 검색" aria-label="컬럼 유형 검색"/>{types.map((item) => <ActionForm key={item.type} action={addNewcustColumn}><input type="hidden" name="boardId" value={boardId}/><input type="hidden" name="type" value={item.type}/><input type="hidden" name="label" value={item.label}/><button>{item.label}</button></ActionForm>)}<p>더 많은 컬럼</p></div></details>; }

function CsvImport({ boardId, groupId }: { boardId: string; groupId: string }) {
  const router = useRouter();
  const [state, submit, pending] = useActionState(importNewcustCsv, initial);
  const [undoState, undo, undoPending] = useActionState(undoNewcustCsv, initial);
  useEffect(() => { if (state.ok || undoState.ok) router.refresh(); }, [state.ok, state.message, undoState.ok, undoState.message, router]);
  return <details><summary>CSV 가져오기</summary><form action={submit} aria-busy={pending}><input type="hidden" name="boardId" value={boardId}/><input type="hidden" name="groupId" value={groupId}/><label>CSV 내용<textarea name="csv" placeholder={'업체명,연락처\n모아기업,02-000-0000'} /></label><button>같은 표로 가져오기</button><p role="status">{state.message}</p></form>{state.ok && state.itemIds?.length ? <form action={undo}><input type="hidden" name="boardId" value={boardId}/><input type="hidden" name="itemIds" value={state.itemIds.join(",")}/><button disabled={undoPending}>마지막 가져오기 되돌리기</button><p role="status">{undoState.message}</p></form> : null}</details>;
}
