import assert from "node:assert/strict";
import test from "node:test";

import { renderProvisionAssets, verifyProvisionAssets } from "./assets.mjs";
import { provisionFixture } from "./test-fixtures.mjs";

test("renders deterministic isolated systemd, Caddy, policy, and runtime config assets", () => {
  const { manifest } = provisionFixture();
  const first = renderProvisionAssets(manifest);
  const second = renderProvisionAssets(manifest);
  assert.deepEqual(first, second);
  assert.match(first.blueUnit.bytes, /User=moawork\n/);
  assert.match(first.blueUnit.bytes, /ConditionPathExists=\/srv\/moawork\/blue\/runtime\/app\/server[.]js/);
  assert.match(first.blueUnit.bytes, /MemoryMax=1073741824/);
  assert.match(first.blueUnit.bytes, /CPUQuota=20%/);
  assert.doesNotMatch(first.blueUnit.bytes, /salespt|hermes/iu);
  assert.equal(first.caddyImport.operation, "append_exact_line");
  assert.match(first.caddySite.bytes, /import \/etc\/caddy\/moawork[.]d\/[*][.]caddy/);
  assert.match(first.polkit.bytes, /moawork-web-blue[.]service/);
  assert.match(first.polkit.bytes, /unit === "caddy[.]service" && verb === "reload"/);
  assert.doesNotMatch(first.polkit.bytes, /"start"/);
  assert.doesNotMatch(first.polkit.bytes, /reload-or-restart/);
  assert.doesNotMatch(first.polkit.bytes, /["'](?:[/*]|org[.]freedesktop[.]systemd1[.][*])["']/u);
  assert.doesNotThrow(() => JSON.parse(first.releaseConfig.bytes));
});

test("binds every generated byte contract to reviewed manifest digests", () => {
  const { manifest } = provisionFixture();
  const verified = verifyProvisionAssets(manifest);
  assert.equal(verified.caddyClosureSha256, manifest.caddy.closureSha256);
  const assets = renderProvisionAssets(manifest);
  const tampered = { ...assets, greenUnit: { ...assets.greenUnit, bytes: `${assets.greenUnit.bytes}# drift\n` } };
  assert.throws(() => verifyProvisionAssets(manifest, tampered), (error) => error.code === "ASSET_DRIFT");
});

test("keeps the global Node executable outside both release slots", () => {
  const { manifest } = provisionFixture();
  const assets = renderProvisionAssets(manifest);
  const config = JSON.parse(assets.releaseConfig.bytes);
  assert.equal(config.nodePath, "/opt/moawork/node-22.23.2/bin/node");
  assert.equal(config.nodeVersion, "v22.23.2");
  assert.equal(config.nodeArch, "x64");
  assert.equal(config.caddyImportLine, "import /etc/caddy/moawork.caddy");
  assert.equal(config.caddySiteFile, "/etc/caddy/moawork.caddy");
  assert.equal(config.caddySiteSha256, manifest.caddy.siteSha256);
  assert.equal(config.caddyClosureSha256, manifest.caddy.closureSha256);
  assert.equal(config.slots.blue.releaseDir, "/srv/moawork/blue");
  assert.equal(config.slots.green.releaseDir, "/srv/moawork/green");
  assert.equal(config.nodePath.startsWith(config.releaseRoot), false);
});
