import { addLedgerEntry, cancelLedgerEntry, correctLedgerEntry } from "@/app/(app)/settlements/actions";
import type { LedgerEntry, LedgerTotals } from "@/lib/settlements/ledger";

type Row = { settlementId: string; expected: number; totalRevenue: number; entries: LedgerEntry[]; totals: LedgerTotals };
const won = (value: number) => `${value.toLocaleString("ko-KR")}원`;
const status = { unpaid: "미입금", partial: "부분 입금", paid: "입금 완료", overpaid: "초과 입금" } as const;

export function LedgerTable({ rows, canManage }: { rows: Row[]; canManage: boolean }) {
  if (rows.length === 0) return <div className="rounded-2xl border p-8 text-center" style={{borderColor:"var(--mw-line)",background:"var(--mw-card)"}}><p className="font-semibold">정산 정보가 아직 없어요.</p><p className="mt-1 text-sm" style={{color:"var(--mw-sub)"}}>업무에서 실행액과 수수료율을 입력하면 원장이 여기에 생겨요.</p></div>;
  return <div className="space-y-4">{rows.map((row) => <section key={row.settlementId} className="rounded-2xl border p-4" style={{borderColor:"var(--mw-line)",background:"var(--mw-card)"}}>
    <header className="flex flex-wrap items-center gap-3"><div><p className="text-xs" style={{color:"var(--mw-sub)"}}>정산 {row.settlementId.slice(0,8)}</p><h2 className="font-semibold">{status[row.totals.status]} · 미수 {won(row.totals.outstanding)}</h2></div><div className="ml-auto text-right text-sm"><p>수수료 예정(자동 계산) {won(row.expected)}</p><p style={{color:"var(--mw-sub)"}}>입금(직접 입력) {won(row.totals.paid)} · 총매출(자동 계산) {won(row.totalRevenue)}</p></div></header>
    {canManage ? <form action={addLedgerEntry} className="mt-4 flex flex-wrap gap-2"><input type="hidden" name="settlementId" value={row.settlementId}/><select name="kind" className="rounded-lg border px-3 py-2"><option value="payment">입금</option><option value="refund">환불</option><option value="adjustment">조정</option></select><input name="amount" type="number" min="1" step="1" required placeholder="금액(원)" className="rounded-lg border px-3 py-2"/><input name="occurredOn" type="date" required className="rounded-lg border px-3 py-2"/><button className="rounded-lg px-4 py-2 font-semibold" style={{background:"var(--mw-primary)",color:"var(--mw-on-accent)"}}>내역 추가</button></form> : null}
    <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead><tr className="text-left" style={{color:"var(--mw-sub)"}}><th className="py-2">일자</th><th>구분</th><th>출처</th><th className="text-right">금액</th><th>상태</th><th>작업</th></tr></thead><tbody>{row.entries.map((entry) => <tr key={entry.id} className="border-t" style={{borderColor:"var(--mw-line)"}}><td className="py-2">{entry.occurredOn}</td><td>{entry.kind === "payment" ? "입금" : entry.kind === "refund" ? "환불" : "조정"}</td><td>{entry.source === "input" ? "직접 입력" : "자동 계산"}</td><td className="text-right">{won(entry.amount)}</td><td>{entry.status === "posted" ? "반영됨" : "취소됨"}</td><td>{canManage && entry.status === "posted" ? <div className="flex gap-2"><form action={cancelLedgerEntry}><input type="hidden" name="entryId" value={entry.id}/><button className="underline">취소</button></form><details><summary className="cursor-pointer underline">정정</summary><form action={correctLedgerEntry} className="mt-2 flex gap-1"><input type="hidden" name="entryId" value={entry.id}/><input name="amount" type="number" min="1" step="1" required defaultValue={entry.amount} className="w-28 rounded border px-2"/><input name="occurredOn" type="date" required defaultValue={entry.occurredOn} className="rounded border px-2"/><button className="underline">저장</button></form></details></div> : "—"}</td></tr>)}</tbody></table></div>
  </section>)}</div>;
}
